2018-11-02 13:18:07,437 - Server.py - INFO - Запуск сервера 
2018-11-02 13:18:10,567 - Client.py - INFO - Запуск клиентской программы 
2018-11-02 13:18:10,568 - Client.py - INFO - Запрос клиента на подключение к серверу и авторизацию 
2018-11-02 13:18:10,568 - Server.py - INFO - Получено сообщение от клиента 
2018-11-02 13:18:10,568 - Server.py - INFO - Проверка авторизации, соединение разрешено 
2018-11-02 13:18:10,568 - Server.py - INFO - Клиенту передано разрешение на соединение 
2018-11-02 13:18:10,569 - Client.py - INFO - Получение ответа сервера с разрешением или запретом подключения 
2018-11-02 13:18:10,569 - Client.py - INFO - Посылка клиентом сервисного сообщения о присутствии 
2018-11-02 13:18:10,569 - Client.py - INFO - Клиентская программа закрыта 
2018-11-02 16:09:01,880 - Client.py - INFO - Запуск клиентской программы 
2018-11-02 16:10:09,475 - Server.py - INFO - Запуск сервера 
2018-11-02 16:10:12,836 - Client.py - INFO - Запуск клиентской программы 
2018-11-02 16:10:12,837 - Client.py - INFO - Запрос клиента на подключение к серверу и авторизацию 
2018-11-02 16:10:12,838 - Server.py - INFO - Получено сообщение от клиента 
2018-11-02 16:10:12,838 - Server.py - INFO - Проверка авторизации, соединение разрешено 
2018-11-02 16:10:12,838 - Server.py - INFO - Клиенту передано разрешение на соединение 
2018-11-02 16:10:12,838 - Server.py - WARNING - Ошибка в параметрах связи, работоспособность восстановлена 
2018-11-02 16:10:12,838 - Client.py - INFO - Получение ответа сервера с разрешением или запретом подключения 
2018-11-02 16:10:12,839 - Client.py - INFO - Посылка клиентом сервисного сообщения о присутствии 
2018-11-02 16:10:12,839 - Client.py - INFO - Клиентская программа закрыта 
