2018-11-02 13:19:40,456 - Server.py - INFO - Запуск сервера 
2018-11-02 13:19:43,237 - Server.py - INFO - Получено сообщение от клиента 
2018-11-02 13:19:43,237 - Server.py - INFO - Проверка авторизации, соединение разрешено 
2018-11-02 13:19:43,238 - Server.py - INFO - Клиенту передано разрешение на соединение 
2018-11-02 16:03:56,564 - Server.py - INFO - Запуск сервера 
2018-11-02 16:04:00,583 - Server.py - INFO - Получено сообщение от клиента 
2018-11-02 16:04:00,584 - Server.py - INFO - Проверка авторизации, соединение разрешено 
2018-11-02 16:04:00,584 - Server.py - INFO - Клиенту передано разрешение на соединение 
2018-11-02 16:05:53,099 - Server.py - INFO - Запуск сервера 
2018-11-02 16:05:56,676 - Server.py - INFO - Получено сообщение от клиента 
2018-11-02 16:05:56,676 - Server.py - INFO - Проверка авторизации, соединение разрешено 
2018-11-02 16:05:56,676 - Server.py - INFO - Клиенту передано разрешение на соединение 
2018-11-02 16:05:56,677 - Server.py - WARNING - Ошибка в параметрах связи работоспособность восстановлена 
2018-11-02 16:11:24,200 - Server.py - INFO - Запуск сервера 
2018-11-02 16:11:27,587 - Server.py - INFO - Получено сообщение от клиента 
2018-11-02 16:11:27,587 - Server.py - INFO - Проверка авторизации, соединение разрешено 
2018-11-02 16:11:27,587 - Server.py - INFO - Клиенту передано разрешение на соединение 
2018-11-02 16:11:27,587 - Server.py - WARNING - Ошибка в параметрах связи, работоспособность восстановлена 
